spring:
  application:
    name: customer_update


kafka:
  bootstrap-servers: localhost:29092
  sasl:
    username: admin
    password: admin-secret
  consumer:
    group-id: customer-update-consumer-group

server:
  port: 8083